"""Common utilities."""
import inspect
import sys
import time
from typing import Iterable

import numpy as np
import requests


def printerr(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


_t: float = None


def tic() -> None:
    """Records current time for toc()."""
    global _t
    _t = time.monotonic()


def toc() -> None:
    """Prints the time elapsed since calling tic()."""
    printerr('Took {:.1f} seconds'.format(time.monotonic() - _t))


def interactive() -> bool:
    """Indicates whether this run is batch or interactive shell."""
    return hasattr(sys, "ps1")


def flatten(a):
    """Flattens a list or an iterable."""
    if isinstance(a, list):
        return [c for b in a for c in b]
    return (c for b in a for c in b)


_done = 0
_done_t = 0
_done_checkpoints = {10 ** i for i in range(9)}
_done_checkpoints |= {3 * x for x in _done_checkpoints}


def done(fmt: str = None):
    global _done, _done_t
    if _done == 0:
        _done_t = time.monotonic()
    _done += 1
    if _done in _done_checkpoints:
        if fmt is None:
            fmt = 'Done {} ({:.1f}s)'
        printerr(fmt.format(_done, time.monotonic() - _done_t))


def done_reset():
    global _done
    _done = 0


def hist(a, bins=10) -> None:
    from plotly import express as px
    hy, hx = np.histogram(a, bins)
    px.bar(x=hx[:-1], y=hy).show()


def linenum():
    """Returns the current line number."""
    return inspect.currentframe().f_back.f_lineno


class timtim:
    def __init__(self):
        self.t = time.monotonic()
        self.checkpoints = {a * (10 ** b) for a in (1, 2, 5) for b in range(8)}
        self.i = 0

    def done(self):
        self.i += 1
        if self.i in self.checkpoints:
            print('\r{} ({:.1f}s)'.format(
                self.i, time.monotonic() - self.t), end='')


def get_lnsrv(addr: str, end='END') -> Iterable[str]:
    """Returns lines generated by Line Server (lnsrv) as an iterable."""
    line = requests.get(addr).text.strip()
    while line != end:
        yield line
        line = requests.get(addr).text.strip()
