"""Common utilities."""
import gzip
import inspect
import sys
import time
from contextlib import contextmanager
from typing import IO, Iterable

import numpy as np
import requests


def printerr(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


_t: float = None


def tic() -> None:
    """Records current time for toc()."""
    global _t
    _t = time.monotonic()


def toc() -> None:
    """Prints the time elapsed since calling tic()."""
    printerr('Took {:.1f} seconds'.format(time.monotonic() - _t))


def interactive() -> bool:
    """Indicates whether this run is batch or interactive shell."""
    return hasattr(sys, "ps1")


def flatten(a):
    """Flattens a list or an iterable."""
    if isinstance(a, list):
        return [c for b in a for c in b]
    return (c for b in a for c in b)


_done = 0
_done_t = 0
_done_checkpoints = {10**i for i in range(9)}
_done_checkpoints |= {3 * x for x in _done_checkpoints}


def done(fmt: str = None):
    global _done, _done_t
    if _done == 0:
        _done_t = time.monotonic()
    _done += 1
    if _done in _done_checkpoints:
        if fmt is None:
            fmt = 'Done {} ({:.1f}s)'
        printerr(fmt.format(_done, time.monotonic() - _done_t))


def done_reset():
    global _done
    _done = 0


def hist(a, bins=10) -> None:
    from plotly import express as px
    hy, hx = np.histogram(a, bins)
    px.bar(x=hx[:-1], y=hy).show()


def linenum():
    """Returns the current line number."""
    return inspect.currentframe().f_back.f_lineno


def mylog(*args):
    fr = inspect.currentframe().f_back
    ln = fr.f_lineno
    fl = fr.f_code.co_filename
    print(f'{fl}:{ln}', file=sys.stderr)
    print('AMIT:', *args, file=sys.stderr)


_TIMTIM_CHECKPOINTS = \
    frozenset(a * (10 ** b) for a in (1, 2, 5) for b in range(10))


class timtim:
    def __init__(self):
        self.t = time.monotonic()
        self.i = 0

    def increment(self):
        self.i += 1
        if self.i in _TIMTIM_CHECKPOINTS:
            print('\r{} ({:.1f}s)'.format(self.i,
                                          time.monotonic() - self.t),
                  end='')

    def done(self):
        print('\r{} ({:.1f}s)'.format(self.i, time.monotonic() - self.t))

    def __enter__(self):
        pass

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.done()


@contextmanager
def timer(prefix=None):
    t = time.monotonic()
    yield
    t = time.monotonic() - t
    if prefix is not None:
        print('{:15} '.format(prefix), end='')
    if t < 0.001:
        print('{:.1f}us'.format(t * 1000000))
    elif t < 1:
        print('{:.1f}ms'.format(t * 1000))
    elif t < 60:
        print('{:.1f}s'.format(t))
    else:
        print('{:.1f}m'.format(t / 60))


def get_lnsrv(addr: str, end='END') -> Iterable[str]:
    """Returns lines generated by Line Server (lnsrv) as an iterable."""
    line = requests.get(addr).text.strip()
    while line != end:
        yield line
        line = requests.get(addr).text.strip()


def zopen(path: str, mode: str = 'rt') -> IO:
    """Opens a file for I/O. If path has a gz/gzip suffix, uses the gzip
    library."""
    if path.endswith('.gz') or path.endswith('.gzip'):
        if mode.startswith('w'):
            return gzip.open(path, mode, compresslevel=1)
        return gzip.open(path, mode)
    return open(path, mode)
